name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name:
          - ubuntu-latest-stable
          - windows-latest-stable
        include:
          - name: ubuntu-latest-stable
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
            rustflags: -D warnings
          - name: windows-latest-stable
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
            rustflags: -D warnings

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.name }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: clippy

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --all-targets --target=${{ matrix.target }}
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
